### ISSUE TITLE
Multiplayer and singleplayer issues

### ISSUE THREAD

**Issue by KingBubb1es** [kerbybit/MinecwaftOwO#4]
Whenever a join a sever my game crashes, I went on single player worlds to see if a would crash there, but every time that I joined I would get stuck in a block.

I know this mod is meant for a meme, but I really wan't 2 use it!

**Comment by kerbybit** [comment]
what other mods are you using? there is a known issue with frames+ and its custom text rendering because both mods inject into the same place in the code and we do not plan on fixing that issue

**Comment by kerbybit** [comment]
Closing this issue due to lack of information
