### ISSUE TITLE
i cant turn  it off

### ISSUE THREAD

**Issue by zombot-is-cool** [kerbybit/MinecwaftOwO#7]
it always goes to "minyecwaftowo" when to toggle you need "minecwaftowo" so i cant turn it off

**Comment by starzorrow** [comment]
just type minecwaftowo it should work anyway

**Comment by kerbybit** [comment]
like stated in the [readme](https://github.com/kerbybit/MinecwaftOwO/blob/master/README.md) the mod replaces ALL text including the text you are about to send but it only changes it visually. Just use tab to complete the command and hit enter and it will toggle off.

I will make this more clear in the readme
